steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://finance-backend-930725375338.us-central1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyDytU0fR26RzappXDmVr1omLdb0M8BZArc'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=aifin-project-7321a.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=aifin-project-7321a'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=aifin-project-7321a.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=98752190715'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:98752190715:web:cf9933d73c437d94cbf85e'
      - '--build-arg'
      - 'NEXT_PUBLIC_TENANT_HEADER_NAME=X-Tenant-ID'
      - '--build-arg'
      - 'NEXT_PUBLIC_DEFAULT_TENANT_ID=default'
      - '-t'
      - 'us-central1-docker.pkg.dev/aifin-project/finance-repo/finance-frontend:latest'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/aifin-project/finance-repo/finance-frontend:latest'
